/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoDemoTanstackQueryRouteImport } from './routes/_demo/demo.tanstack-query'
import { Route as DemoDemoTableRouteImport } from './routes/_demo/demo.table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDemoTanstackQueryRoute = DemoDemoTanstackQueryRouteImport.update({
  id: '/_demo/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDemoTableRoute = DemoDemoTableRouteImport.update({
  id: '/_demo/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoDemoTableRoute
  '/demo/tanstack-query': typeof DemoDemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoDemoTableRoute
  '/demo/tanstack-query': typeof DemoDemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_demo/demo/table': typeof DemoDemoTableRoute
  '/_demo/demo/tanstack-query': typeof DemoDemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/table' | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/table' | '/demo/tanstack-query'
  id: '__root__' | '/' | '/_demo/demo/table' | '/_demo/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoDemoTableRoute: typeof DemoDemoTableRoute
  DemoDemoTanstackQueryRoute: typeof DemoDemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo/demo/tanstack-query': {
      id: '/_demo/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoDemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo/demo/table': {
      id: '/_demo/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoDemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoDemoTableRoute: DemoDemoTableRoute,
  DemoDemoTanstackQueryRoute: DemoDemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
